"""empty message

Revision ID: 12e6489d20bc
Revises: 6a3c4ce8db7f
Create Date: 2021-07-25 23:07:21.717774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e6489d20bc'
down_revision = '6a3c4ce8db7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_tags', 'is_active')
    op.add_column('app_users', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('app_users', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('app_users', sa.Column('updated_at', sa.Date(), nullable=True))
    op.drop_column('app_users', 'budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('app_users', 'updated_at')
    op.drop_column('app_users', 'is_active')
    op.drop_column('app_users', 'created_at')
    op.add_column('app_tags', sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
