"""empty message

Revision ID: 2118239751d1
Revises: 6dec45ef2f87
Create Date: 2021-07-26 00:23:18.719515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2118239751d1'
down_revision = '6dec45ef2f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['app_roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user_roles')
    op.drop_table('app_roles')
    # ### end Alembic commands ###
